[package]
name = "printpdf"
version = "0.2.2"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
repository = "https://github.com/fschutt/printpdf"
homepage = "https://github.com/fschutt/printpdf"
license = "MIT"
readme = "README.md"
description = "Rust library for writing PDF files"

[dependencies]
lopdf = "0.15.1"
freetype-rs = "0.17.0"
error-chain = "0.11.0"
chrono = "0.4.0"
rand = { version = "0.4.2", default-features = false }
log = "0.4.1"
image = "0.18.0"

[features]
clippy = []

[badges]
travis-ci = { repository = "fschutt/printpdf" }