[package]
name = "printpdf"
version = "0.1.0"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
repository = "https://github.com/sharazam/printpdf"
homepage = "https://github.com/sharazam/printpdf"
license = "GPL"
readme = "README.md"
description = "Library for writing PDF files"

[dependencies]
lopdf = { git = "https://github.com/J-F-Liu/lopdf" }
freetype-rs = "0.11.*"
log = "0.3.*"
error-chain = "0.10.*"
chrono = "0.3.1"
rand = "0.3.15"
num = "0.1.37"

[[bin]]
doc = false
name = "printpdf"
path = "src/main.rs"