[package]
name = "printpdf"
version = "0.1.2"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
repository = "https://github.com/sharazam/printpdf"
homepage = "https://github.com/sharazam/printpdf"
license = "MIT"
readme = "README.md"
description = "Rust library for writing PDF files"

[dependencies]
lopdf = "0.10.0"
freetype-rs = "0.13.0"
error-chain = "0.10.*"
chrono = "0.3.0"
rand = "0.3.15"
num = "0.1.37"
svg = "0.5.6"
log = "0.3.8"
image = "0.14.0"

[features]
clippy = []

[[bin]]
doc = false
name = "printpdf"
path = "src/main.rs"
