[package]
name = "printpdf"
version = "0.2.8"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
repository = "https://github.com/fschutt/printpdf"
homepage = "https://github.com/fschutt/printpdf"
license = "MIT"
readme = "README.md"
description = "Rust library for writing PDF files"

[dependencies]
lopdf = { git = "https://github.com/fschutt/lopdf", default-features = false }
rusttype = { version = "0.7.2", default-features = false }
time = { version = "0.1.40", default-features = false }
log = { version = "0.4.1", optional = true }

[dependencies.image]
version = "0.19.0"
default-features = false
features = ["gif_codec", "jpeg", "png_codec", "pnm", "tiff", "bmp"]
optional = true

[features]
clippy = []
logging = ["log"]
embedded_images = ["image"]
default = ["embedded_images"]

[badges]
travis-ci = { repository = "fschutt/printpdf" }
appveyor = { repository = "fschutt/printpdf" }

[package.metadata.docs.rs]
all-features = true