[package]
name = "printpdf"
version = "0.1.0"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
repository = "https://github.com/sharazam/printpdf"
homepage = "https://github.com/sharazam/printpdf"
license = "GPL"
readme = "README.md"
description = "Library for writing PDF files"

[dependencies]
lopdf = { git = "https://github.com/sharazam/lopdf" }
freetype-rs = "0.11.*"
log = "0.3.*"
error-chain = "0.10.*"

[[bin]]
doc = false
name = "printpdf"