[package]
name = "printpdf"
version = "0.2.0"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
repository = "https://github.com/sharazam/printpdf"
homepage = "https://github.com/sharazam/printpdf"
license = "MIT"
readme = "README.md"
description = "Rust library for writing PDF files"

[dependencies]
lopdf = { git = "https://github.com/fschutt/lopdf" }
freetype-rs = "0.16.0"
error-chain = "0.11.*"
chrono = "0.4.0"
rand = "0.3.17"
num = "0.1.40"
svg = "0.5.7"
log = "0.3.8"
image = "0.17.0"

[features]
clippy = []

[[bin]]
doc = false
name = "printpdf"
path = "src/main.rs"
