error_on_line_overflow=false
fn_brace_style = "AlwaysNextLine"
item_brace_style = "AlwaysNextLine"
control_brace_style = "ClosingNextLine"
fn_single_line = true
fn_return_indent = "WithWhereClause"
fn_args_density = "Vertical"
fn_args_layout = "BlockAlways"
type_punctuation_density = "Compressed"
where_density = "Compressed"
where_pred_indent = "Block"
where_indent = "Inherit"
struct_trailing_comma = "Always"
struct_lit_trailing_comma = "Always"
struct_lit_style = "Visual"
struct_lit_multiline_style = "ForceMulti"
generics_indent = "Block"
report_todo = "Never"
report_fixme = "Always"
# reorder_imports = true
reorder_imported_names = true
chain_base_indent = "Visual"
chain_indent = "Block"
single_line_if_else_max_width = 0
force_format_strings = true
take_source_hints = false
wrap_comments = true
match_block_trailing_comma = true
spaces_around_ranges = true
use_try_shorthand = true
condense_wildcard_suffices = true
